#  Numpy - Numerical Python 

In [5]:
a = np.array([1, 2, 3,4,5], ndmin = 2) 

print(a)

[[1 2 3 4 5]]


In [6]:
a = np.array([1, 2, 3], dtype = complex) 

print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [ ]:
NumPy

In [4]:
# import numpy library

import numpy as np

E:\Innomatics data sci\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
E:\Innomatics data sci\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
E:\Innomatics data sci\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
# check the version of numpy

print(np.version.version)
print(np.__version__)

1.21.5
1.21.5


## Upgrade Numpy:
```
    pip install -- upgrade numpy
    pip install -- upgrade numpy --ignore-installed
    pip install -- upgrade numpy --ignore-installed --user
```

In [6]:
import numpy as np

In [2]:
print(np.version.version)

1.23.4


In [ ]:
print(dir)

In [41]:

array1 = np.array(range(0,24)).reshape(4,2,3)
print (array1)
print('shape of the array:',array1.shape)
 
print('-'*40)
    
    
array1 = np.array(range(0,24)).reshape(1,1,24)
print (array2)
print('shape of the array:',array2.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
shape of the array: (4, 2, 3)
----------------------------------------
[[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
   23]]]
shape of the array: (1, 1, 24)


In [38]:
array1 = np.array(range(0,24)).reshape(4,2,3)
print(array1)

print('-'*40)

array2 = np.array(range(0,24)).reshape(1,1,24)
print(array2)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
----------------------------------------
[[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
   23]]]


### Class Assignment

In [9]:
#Que1.Create a 2-D array of float32 type

type1 = np.array([[2,3,4],[5,6,7]]).dtype = np.float32
print(type1)
                  

<class 'numpy.float32'>


In [12]:
#Que2.Create the below array using more than one approach:
#[  0.   12.5  25.   37.5  50.   62.5  75.   87.5 100. ]


list = [0,12.5,25,37.5,50,62.5,75,87.5,100]
arr1 = np.diag(np.array([0,12.5,25,37.5,50,62.5,75,87.5,100]))
print(arr1)
print(np.diag(arr1))

# or
print('-'* 50)

array1 = np.linspace(0,100,9)
print(array1)

# or
print('-'* 50)

x = np.arange(0,101,12.5)
print(x)

[[  0.    0.    0.    0.    0.    0.    0.    0.    0. ]
 [  0.   12.5   0.    0.    0.    0.    0.    0.    0. ]
 [  0.    0.   25.    0.    0.    0.    0.    0.    0. ]
 [  0.    0.    0.   37.5   0.    0.    0.    0.    0. ]
 [  0.    0.    0.    0.   50.    0.    0.    0.    0. ]
 [  0.    0.    0.    0.    0.   62.5   0.    0.    0. ]
 [  0.    0.    0.    0.    0.    0.   75.    0.    0. ]
 [  0.    0.    0.    0.    0.    0.    0.   87.5   0. ]
 [  0.    0.    0.    0.    0.    0.    0.    0.  100. ]]
[  0.   12.5  25.   37.5  50.   62.5  75.   87.5 100. ]
--------------------------------------------------
[  0.   12.5  25.   37.5  50.   62.5  75.   87.5 100. ]
--------------------------------------------------
[  0.   12.5  25.   37.5  50.   62.5  75.   87.5 100. ]


In [10]:
#QUE3.Print the Numpy version

print(np.version.version)

1.23.4


In [13]:
#que4.Create a diagonal array with the below value in the diagonal:
#[10.5, 17.5, 24.5, 31.5, 38.5, 45.5]

array1 = np.linspace(10.5,45.5,6)
print(array1)
print(np.diag(array1))

[10.5 17.5 24.5 31.5 38.5 45.5]
[[10.5  0.   0.   0.   0.   0. ]
 [ 0.  17.5  0.   0.   0.   0. ]
 [ 0.   0.  24.5  0.   0.   0. ]
 [ 0.   0.   0.  31.5  0.   0. ]
 [ 0.   0.   0.   0.  38.5  0. ]
 [ 0.   0.   0.   0.   0.  45.5]]


In [30]:
#Que5.Create a (9,1) array and reshape it to (3,3).

print(np.array(range(0,9)))
print(np.array(range(0,9)).reshape(3,3))

print('-'*50)

x = np.arange(9).reshape(9,1)
print(x,x.reshape(3,3),sep= '\n')

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------------------------------------
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [37]:
# create an 1 D array with values from 50 to 99
print(np.array(range(50,100)))

print('-'*50 )

array1d = np.arange(50,100)
print(array1d)



print(array1d[0])
print(array1d[-1])
print(array1d[9])
print(array1d[14])
print(array1d[19:50:10])
print(array1d[range(19,50,10)])
print(array1d[[19,29,39,49]])

print(array1d.shape)
len(array1d.shape)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]
--------------------------------------------------
[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]
50
99
59
64
[69 79 89 99]
[69 79 89 99]
[69 79 89 99]
(50,)


1

In [35]:
array2d = array1d.reshape(5,10)
print(array2d)

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


# Assignment question

In [1]:
# list
# remove values from index pos - 0, 4, 5 

mylist1 = [12,24,35,70,88,120,155]

In [2]:
mylist1 = [12,24,35,70,88,120,155]
[mylist1.remove(y) for y in [mylist1[x] for x in [0,4,5]]]

[None, None, None]

In [3]:
mylist1 = [12,24,35,70,88,120,155]
[y for y in [mylist1[x] for x in [0,4,5]]]

[12, 88, 120]

In [4]:
[z for z in mylist1 if z not in [mylist1[x] for x in [0,4,5]]]

[24, 35, 70, 155]

In [5]:
# f(n) = f(n-1) + f(n-2) where n>1

n = 9 # input
# Output = 13

x = list(range(1, n+1))
print(x[n-1]+x[n-2])

17


In [ ]:
0 1 1 2 3 5 8 13 21 34 55 89  # ibonacci series